import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Boat",
  description: "Generated by krishna kumar for the  password saver !",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="./boat.png" type="image/x-icon" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
